config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:create, :destroy]
  resources :users
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  resources :todo_lists do
    resources :todo_items do
      member do
        patch :complete
      end
    end
  end

  root "todo_lists#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  include ErrorsHandler
  self.abstract_class = true
end

app/models/concerns/errors_handler.rb
module ErrorsHandler
  extend ActiveSupport::Concern
  module ClassMethods
    errors_arr = {}
    define_method(:add_errors) { |errors| errors_arr = errors }
    define_method(:get_errors) { errors_arr }
  end
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  belongs_to :todo_list

  def completed?
    !self.completed_at.blank?
  end
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
  belongs_to :user

  has_many :todo_items, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_many :todo_lists ,dependent: :destroy

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  before_save { self.email = email.downcase }
  has_secure_password

  validates :name, presence: true, length: { maximum: 50 }


  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  protect_from_forgery with: :null_session

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by_email(params[:email])
    respond_to do |format|
      if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        format.html{ redirect_to root_url, notice: "Logged in!"}
      else
        format.js
        format.html {render :new}
      end
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :set_todo_list
  before_action :update_params, only: [:update]
  before_action :set_todo_item, except: [:create]


  def create
    @todo_item = @todo_list.todo_items.create(todo_item_params)
    redirect_to @todo_list
  end

  def destroy
    @todo_item = @todo_list.todo_items.find(params[:id])
    if @todo_item.destroy
      flash[:success] = "Todo List item was deleted."
    else
      flash[:error] = "Todo List item could not be deleted."
    end
    redirect_to @todo_list
  end

  def update
    if @todo_item.update(update_params)
      render json: {
          status: 200
      }
    else
      render json: {
          status: 422
      }
    end
  end

  def complete
    @todo_item.update_attribute(:completed_at, Time.now)
    redirect_to @todo_list, notice: "Todo item completed"
  end

  private

  def set_todo_list
    @todo_list = TodoList.find(params[:todo_list_id])
  end

  def update_params
    params[:todo_item].permit(:content)
  end

  def todo_item_params
    params[:todo_item].permit(:content)
  end

  def set_todo_item
    @todo_item = @todo_list.todo_items.find(params[:id])
  end

end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]

  # GET /todo_lists
  # GET /todo_lists.json
  def index
    if current_user
      @todo_lists = TodoList.where(user_id: current_user.id)
    else
      redirect_to login_path
    end
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
  end

  # GET /todo_lists/new
  def new
    @todo_list = TodoList.new
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    respond_to do |format|
      if current_user.todo_lists.create(todo_list_params)
        format.html { redirect_to root_path, notice: 'Todo list was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Todo list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_list_params
      params.require(:todo_list).permit(:title, :description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html{ redirect_to root_url, notice: 'User was successfully created' }
        format.json { render :show, status: :created, location: @user }
      else
        ApplicationRecord.add_errors(@user.errors)
        format.js
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.js {}
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.js {}
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_header.html.erb
<div class="appHeader">
  <%= stylesheet_link_tag "_header" %>
  <div class="container">
    <nav class="navbar navbar-expand-sm mr-auto navbar-dark ">
      <ul class="navbar-nav w-100">
        <li class="nav-item active">
          <a class="nav-link" href="/"><i class="fa fa-home fa-2x"></i></a>
        </li>
        <li class="nav-item ml-auto">
          <% if current_user %>
          <li class="nav-item">
            <a class="nav-link active" href="/logout">Logout<i class="fa fa-sign-out fa-2x"></i></a>
          </li>
        <% else %>
          <a class="nav-link active" href="/login">Sign in <i class="fa fa-sign-in fa-2x"></i></a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="/signup">Sign up <i class="fa fa-external-link fa-2x"></i></a>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo</title>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>
  <%= render "header" %>
<div class="content">
<p id="notice"><%= notice %></p>
<div class="container">
  <%= yield %>
</div>
</div>

</body>
</html>

app/views/todo_items/_form.html.erb
<%= form_for([@todo_list, @todo_list.todo_items.build], :html=>{id: "submit_form",multipart: true, remote: true}) do |f| %>
  <%= f.text_field :content, placeholder: "New Todo" %>
  <%= f.submit  %>
<% end %>

app/views/todo_items/_todo_item.html.erb
<div class="row clearfix" id="<%= todo_item.id %>">
  <% if todo_item.completed? %>
    <div class="complete">
      <%= link_to complete_todo_list_todo_item_path(@todo_list, todo_item.id), method: :patch, remote: true do %>
        <i style="opacity: 0.4;" class="fa fa-check"></i>
      <% end %>
    </div>
    <div class="todo_item">
      <p style="opacity: 0.4;"><strike><%= todo_item.content %></strike></p>
    </div>
    <div class="trash">
      <%= link_to todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, remote: true do %>
        <i class="fa fa-trash"></i>
      <% end %>
    </div>
  <% else %>
    <div class="complete">
      <%= link_to complete_todo_list_todo_item_path(@todo_list, todo_item.id), method: :patch, remote: true do %>
        <i class="fa fa-circle-thin"></i>
      <% end %>
    </div>
    <div class="todo_item">
      <p><%= todo_item.content %></p>
    </div>
    <div class="trash">
      <%= link_to todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, remote: true do %>
        <i class="fa fa-trash"></i>
      <% end %>
    </div>
  <% end %>

  <script>
    (function () {
      let clicked;
      let contentP;
      $(".todo_item > p")
        .click(function (e) {
          if(e.target.tagName !== "STRIKE" && !e.target.children[0] ) {
            contentP = $(this).text();
            clicked = $(this).parents('.row').attr('id');
            $(this).attr('contenteditable', 'true');
          }
        })
        .blur(function () {
          const changedText = $(this).text();
          if (changedText.length > 0 && changedText !== contentP && (clicked === $(this).parents('.row').attr('id'))) {

            $.ajax({
              type: "PUT",
              url: `/todo_lists/<%=todo_item.todo_list_id%>/todo_items/${clicked}>`,
              xhrFields: {
                withCredentials: true
              },
              data: {todo_item: {content: changedText}},
              success: (data) => {
                $('#notice').html('Item updated');
                setTimeout(() => {
                  $('#notice').html('Item updated').html('')
                }, 3000)
              },
              error: (data) => errorResponce({'Sorry': ["Something went wrong"]})
            })

          } else {
            $(this).html(contentP);
          }
        })
    })()
  </script>

</div>

app/views/todo_lists/_form.html.erb
<%= form_with(model: todo_list, local: true) do |form| %>
  <% if todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

      <ul>
      <% todo_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/todo_lists/edit.html.erb
<h1 class="todo_list_title">Editing Todo List</h1>
<div class="forms">
  <%= render 'form', todo_list: @todo_list %>
</div>
<div class="links">
  <%= link_to 'Cancel', todo_lists_path %>
</div>

app/views/todo_lists/index.html.erb
<% @todo_lists.each do |todo_list| %>
  <div class="index_row clearfix">
    <h2 class="todo_list_title"><%= link_to todo_list.title, todo_list %></h2>
    <p class="todo_list_sub_title"><%= todo_list.description %></p>
  </div>
<% end %>
<div class="links">
  <%= link_to "New Todo List", new_todo_list_path %>
</div>

app/views/todo_lists/new.html.erb
<h1 class = "todo_list_title">New Todo List</h1>

<div class="forms">
  <%= link_to todo_lists_path, class:"goBack" do %>
    <i class="fa  fa-arrow-left fa-2x goBackIcon"></i>
  <%end %>
<%= render 'form', todo_list: @todo_list %>
</div>

app/views/todo_lists/show.html.erb
<%=link_to edit_todo_list_path(@todo_list), class:"edit" do %>
  <i class="fa fa-pencil-square-o fa-2x editListIcon"></i>
  <span class="tooltiptext">Edit Todo List</span>
<%end %>

<%= link_to todo_list_path(@todo_list), method: :delete, class:"remove", data: {confirm: "are you sure?"} do %>
  <i class="fa fa-close fa-2x deleteListIcon"></i>
  <span class="tooltiptext">Delete Todo List</span>
<%end %>

<%= link_to todo_lists_path, class:"goBack" do %>
  <i class="fa  fa-arrow-left fa-2x goBackIcon"></i>
<%end %>

<h2 class="todo_list_title"><%= @todo_list.title %></h2>
<p class="todo_list_sub_title"><%= @todo_list.description %></p>

<div id="todo_items_wrapper">
  <%= render @todo_list.todo_items %>
  <div id="form">
    <%= render "todo_items/form" %>
  </div>
</div>

app/views/users/_form.html.erb
<div class="newUser">
  <%= form_with(model: user, html: {class: 'newUserForm', remote: true}) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, class: @user.errors[:email]?nil:"error" %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password,  class: @user.errors[:password]?nil:"error"%>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, class: @user.errors[:password_confirmation]?nil:"error" %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name,  class: @user.errors[:name]?nil:"error"%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/users/create.js.erb
errorResponce(<%=raw ApplicationRecord.get_errors.to_json%>);

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class = "newUserPage">
<h1 class="header">Registration</h1>

<%= render 'form', user: @user %>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>